#!/usr/bin/env node
// Builds docs/progress.md from the requirements document and docs/status.json.
//
//   node tools/progress.mjs            (run from the project root)
//
// docs/status.json keeps one entry per requirement that has any progress; everything else
// counts as "not started". Unknown IDs or unknown statuses stop the script, so the tracker
// cannot drift away from the requirements document.
import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';

export const STATUSES = ['done', 'built', 'partial', 'todo'];
const LABEL = { done: 'Done', built: 'Built', partial: 'Partial', todo: 'Not started' };
const PHASES = [
  ['M', 'MVP launch'],
  ['2', 'Phase 2'],
  ['3', 'Phase 3'],
  ['4', 'Phase 4'],
];

export function parseRequirements(md) {
  const version = md.match(/\*\*Version ([0-9.]+)/)?.[1] ?? '?';
  const modules = [];
  let current = null;
  for (const line of md.split(/\r?\n/)) {
    const mod = line.match(/^### ([A-Z]+): (.*)$/);
    if (mod) {
      current = { code: mod[1], title: mod[2].trim(), items: [] };
      modules.push(current);
      continue;
    }
    const item = line.match(/^- \[[ xX]\] \*\*([A-Z]+-\d+)\*\* \[(M|2|3|4)\] (.*)$/);
    if (item && current) current.items.push({ id: item[1], phase: item[2], text: item[3].replace(/\*\*/g, '').trim() });
  }
  return { version, modules };
}

export function buildReport(reqs, statusFile) {
  const items = statusFile.items ?? {};
  const known = new Set(reqs.modules.flatMap((m) => m.items.map((i) => i.id)));
  for (const [id, entry] of Object.entries(items)) {
    if (!known.has(id)) throw new Error(`status.json mentions ${id}, which is not in the requirements document`);
    if (!STATUSES.includes(entry.status)) throw new Error(`${id} has an unknown status "${entry.status}"`);
  }
  const statusOf = (id) => items[id]?.status ?? 'todo';

  const all = reqs.modules.flatMap((m) => m.items.map((i) => ({ ...i, module: m.code, status: statusOf(i.id), note: items[i.id]?.note ?? '' })));
  const count = (list) => Object.fromEntries(STATUSES.map((s) => [s, list.filter((i) => i.status === s).length]));
  const pct = (n, total) => (total === 0 ? '0%' : `${Math.round((n / total) * 100)}%`);
  const short = (t) => (t.length > 120 ? `${t.slice(0, 117)}…` : t);
  const cell = (t) => t.replace(/\|/g, '\\|');

  const total = all.length;
  const totals = count(all);
  const touched = totals.done + totals.built + totals.partial;
  const out = [];

  out.push('# Vyro Music: build progress', '');
  out.push(`Requirements document version ${reqs.version} · ${total} requirements · updated ${statusFile.meta?.updated ?? 'unknown date'}`, '');
  out.push('This file is generated by `node tools/progress.mjs` from `docs/requirements.md` and `docs/status.json`. Edit `status.json`, not this file.', '');

  out.push('## How to read the statuses', '');
  out.push('| Status | Meaning |', '|---|---|');
  out.push('| **Done** | Finished and verified by tests that have been run |');
  out.push('| **Built** | The code is written (and tested here where possible) but not yet run on a phone or computer, or not yet connected end to end, for example screens that still show demo numbers |');
  out.push('| **Partial** | Only part of the requirement exists; the note says what is missing |');
  out.push('| **Not started** | Nothing built yet |', '');

  out.push('## Summary', '');
  out.push('| | Requirements | Share |', '|---|---:|---:|');
  for (const s of STATUSES) out.push(`| ${LABEL[s]} | ${totals[s]} | ${pct(totals[s], total)} |`);
  out.push(`| **Anything built (done + built + partial)** | **${touched}** | **${pct(touched, total)}** |`, '');

  out.push('### By phase', '');
  out.push('| Phase | Total | Done | Built | Partial | Not started |', '|---|---:|---:|---:|---:|---:|');
  for (const [code, name] of PHASES) {
    const list = all.filter((i) => i.phase === code);
    const c = count(list);
    out.push(`| ${name} | ${list.length} | ${c.done} | ${c.built} | ${c.partial} | ${c.todo} |`);
  }
  out.push('');

  out.push('### By module', '');
  out.push('| Module | Total | Done | Built | Partial | Not started |', '|---|---:|---:|---:|---:|---:|');
  for (const m of reqs.modules) {
    const list = all.filter((i) => i.module === m.code);
    const c = count(list);
    out.push(`| ${m.code}: ${cell(m.title)} | ${list.length} | ${c.done} | ${c.built} | ${c.partial} | ${c.todo} |`);
  }
  out.push('');

  if (statusFile.meta?.next?.length) {
    out.push('## Suggested next steps', '');
    statusFile.meta.next.forEach((n, i) => out.push(`${i + 1}. ${n}`));
    out.push('');
  }

  out.push('## What exists so far', '');
  for (const m of reqs.modules) {
    const list = all.filter((i) => i.module === m.code && i.status !== 'todo');
    if (list.length === 0) continue;
    out.push(`### ${m.code}: ${m.title}`, '');
    out.push('| ID | Phase | Status | Requirement | Where it stands |', '|---|---|---|---|---|');
    for (const i of list) out.push(`| ${i.id} | ${i.phase} | ${LABEL[i.status]} | ${cell(short(i.text))} | ${cell(i.note)} |`);
    out.push('');
  }

  out.push('## Not started', '');
  for (const m of reqs.modules) {
    const ids = all.filter((i) => i.module === m.code && i.status === 'todo').map((i) => i.id);
    if (ids.length > 0) out.push(`- **${m.code}** (${ids.length}): ${ids.join(', ')}`);
  }
  out.push('');
  return out.join('\n');
}

async function main() {
  const root = process.argv[2] ?? '.';
  const reqs = parseRequirements(await readFile(join(root, 'docs/requirements.md'), 'utf8'));
  const status = JSON.parse(await readFile(join(root, 'docs/status.json'), 'utf8'));
  const report = buildReport(reqs, status);
  await writeFile(join(root, 'docs/progress.md'), report);
  const items = Object.values(status.items ?? {});
  console.log(`docs/progress.md written: ${items.filter((i) => i.status === 'done').length} done, ${items.filter((i) => i.status === 'built').length} built, ${items.filter((i) => i.status === 'partial').length} partial`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) await main();
